# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import medication_schedule_pb2 as medication__schedule__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in medication_schedule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MedicationReminderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSchedule = channel.unary_unary(
                '/grpc_client.generated.MedicationReminderService/CreateSchedule',
                request_serializer=medication__schedule__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=medication__schedule__pb2.ScheduleResponse.FromString,
                _registered_method=True)
        self.GetSchedules = channel.unary_unary(
                '/grpc_client.generated.MedicationReminderService/GetSchedules',
                request_serializer=medication__schedule__pb2.GetSchedulesRequest.SerializeToString,
                response_deserializer=medication__schedule__pb2.SchedulesResponse.FromString,
                _registered_method=True)


class MedicationReminderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MedicationReminderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=medication__schedule__pb2.CreateScheduleRequest.FromString,
                    response_serializer=medication__schedule__pb2.ScheduleResponse.SerializeToString,
            ),
            'GetSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedules,
                    request_deserializer=medication__schedule__pb2.GetSchedulesRequest.FromString,
                    response_serializer=medication__schedule__pb2.SchedulesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_client.generated.MedicationReminderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_client.generated.MedicationReminderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MedicationReminderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_client.generated.MedicationReminderService/CreateSchedule',
            medication__schedule__pb2.CreateScheduleRequest.SerializeToString,
            medication__schedule__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_client.generated.MedicationReminderService/GetSchedules',
            medication__schedule__pb2.GetSchedulesRequest.SerializeToString,
            medication__schedule__pb2.SchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
