# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: medication_schedule.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'medication_schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19medication_schedule.proto\x12\x15grpc_client.generated\"\xae\x01\n\x12MedicationSchedule\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\x0fmedication_name\x18\x02 \x01(\t\x12\x11\n\tfrequency\x18\x03 \x01(\x05\x12\x15\n\rduration_days\x18\x04 \x01(\x05\x12\x0f\n\x07user_id\x18\x05 \x01(\x05\x12\x12\n\nstart_date\x18\x06 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x07 \x01(\t\x12\x12\n\ndaily_plan\x18\x08 \x03(\t\"\xa5\x01\n\x15\x43reateScheduleRequest\x12\x17\n\x0fmedication_name\x18\x01 \x01(\t\x12\x11\n\tfrequency\x18\x02 \x01(\x05\x12\x15\n\rduration_days\x18\x03 \x01(\x05\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\x12\x12\n\nstart_date\x18\x05 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x06 \x01(\t\x12\x12\n\ndaily_plan\x18\x07 \x03(\t\"O\n\x10ScheduleResponse\x12;\n\x08schedule\x18\x01 \x01(\x0b\x32).grpc_client.generated.MedicationSchedule\"&\n\x13GetSchedulesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"Q\n\x11SchedulesResponse\x12<\n\tschedules\x18\x01 \x03(\x0b\x32).grpc_client.generated.MedicationSchedule2\xea\x01\n\x19MedicationReminderService\x12g\n\x0e\x43reateSchedule\x12,.grpc_client.generated.CreateScheduleRequest\x1a\'.grpc_client.generated.ScheduleResponse\x12\x64\n\x0cGetSchedules\x12*.grpc_client.generated.GetSchedulesRequest\x1a(.grpc_client.generated.SchedulesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'medication_schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDICATIONSCHEDULE']._serialized_start=53
  _globals['_MEDICATIONSCHEDULE']._serialized_end=227
  _globals['_CREATESCHEDULEREQUEST']._serialized_start=230
  _globals['_CREATESCHEDULEREQUEST']._serialized_end=395
  _globals['_SCHEDULERESPONSE']._serialized_start=397
  _globals['_SCHEDULERESPONSE']._serialized_end=476
  _globals['_GETSCHEDULESREQUEST']._serialized_start=478
  _globals['_GETSCHEDULESREQUEST']._serialized_end=516
  _globals['_SCHEDULESRESPONSE']._serialized_start=518
  _globals['_SCHEDULESRESPONSE']._serialized_end=599
  _globals['_MEDICATIONREMINDERSERVICE']._serialized_start=602
  _globals['_MEDICATIONREMINDERSERVICE']._serialized_end=836
# @@protoc_insertion_point(module_scope)
